#ifndef _PARSER_EXIT_CODE_H_
#define _PARSER_EXIT_CODE_H_

#define PARSER_DIMENSION		 256
#define MAX_STRING_SIZE			 130
#define MAX_NUMBER_SIZE			 13

#define INVALID_PPARSER_POINTER	 -2
#define INVALID_PARSER_POINTER	 -1

#define PARSER_READ_FAIL		 15
#define INVALID_PCHAR_POINTER	 -2
#define INVALID_CHAR_POINTER	 -1

#define NO_SPACES 25

#define SUCCES_LINE_START_WITH_SPACE 20
#define END_LINE 21
#define END_FILE 22
#define NO_SPACES_WITH_END_FILE 26
#define NO_SPACES_WITH_END_LINE 27
#define SUCCES_LINE_END_START_WITH_SPACE 23
#define SUCCES_FILE_END_LINE_START_WITH_SPACE 24
#define SKIPPED 325
#define END_FILE_NO_STRING 28
#define END_LINE_NO_STRING 29
#define END_FILE_NO_NUMBER 28
#define END_LINE_NO_NUMBER 29
#define STRING_OVERFLOW	   30
#define NUMBER_OVERFLOW	   30
#define STRING_READED_END_OF_FILE 31
#define STRING_READED_END_OF_LINE 32
#define NUMBER_READED_END_OF_FILE 31
#define NUMBER_READED_END_OF_LINE 32

#define INVALID_COMMAND 200
#define INVALID_INPUT 201
#define SPACE_DETECTED 201
#define INVALID_INPUT_END_OF_LINE 203
#define INVALID_INPUT_END_OF_FILE 204
#endif // !_PARSER_EXIT_CODE_H_
