#ifndef _CONTROLLER_STATUS_H_
#define _CONTROLLER_STATUS_H_

#define MAX_CAPACITY 10000000
#define MAX_STRUCTS 10
#define INVALID_CONTROLLER_POINTER -1
#define INVALID_PCONTROLLER_POINTER -2
#define INDEX_OUT_OF_BOUNDS_END_FILE 1004
#define STRUCTS_LIMIT_REACHED 1001
#define CAPACITY_LIMIT_REACHED 1002
#define CURRENT_STRUCTURE_UNDEFINED 1003
#define PREVIOUS_STRUCTURE_UNDEFINED 1005
#define NUMBER_OF_STRUCTURES_EXCEEDED 1006
#endif // !_CONTROLLER_STATUS_H_
