#ifndef _EXIT_CODE_STATUS_H_ 
#define _EXIT_CODE_STATUS_H_
typedef enum _BOOLEAN {
	TRUE = 1, FALSE = 0
} BOOLEAN;
#define SUCCES 0
#define INVALID_VECTOR_POINTER - 1
#define INVALID_HEAP_POINTER -1
#define INVALID_TREE_POINTER -1
#define INVALID_NOD_POINTER -1
#define INVALID_LIST_POINTER -1
#define INVALID_HASH_TABLE_POINTER -1
#define INVALID_STRING_POINTER -1
#define INVALID_OUTPUT_PARAMETER_POINTER -1
#define INVALID_FILE_DESCRIPTOR_POINTER -1
#define INVALID_FILE_POINTER -1
#define INVALID_HEAP_POINTER -1

#define INVALID_PHEAP_POINTER -2
#define INVALID_PVECTOR_POINTER -2
#define INVALID_PLIST_POINTER -2
#define INVALID_PNOD_POINTER -2

#define INDEX_OUT_OF_BOUNDS 1000

#define ELEMENT_NOT_FOUND 2

#define FILE_OPEN_ERROR -10
#define MALLOC_ERROR -50

#define INVALID_NEGATIVE_POINTER_VALUE -51
#define INVALID_HASH_FUNCTION_RESULT -30
#define INVALID_RESULT_PARAMETER_POINTER -10


typedef int STATUS_CODE;




#endif // _EXIT_CODE_STATUS_H_
